package it.vantaggi.scoreboardessential.database

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34])
class TopScorerFilterTest {
    private lateinit var db: AppDatabase
    private lateinit var dao: PlayerDao
    private lateinit var attackRole: Role
    private lateinit var defenseRole: Role

    @Before
    fun createDb() =
        runBlocking {
            val context = ApplicationProvider.getApplicationContext<Context>()
            db =
                Room
                    .inMemoryDatabaseBuilder(context, AppDatabase::class.java)
                    .allowMainThreadQueries()
                    .build()
            dao = db.playerDao()

            // Setup Roles
            attackRole = Role(name = "Striker", category = "ATTACCO")
            defenseRole = Role(name = "Defender", category = "DIFESA")
            dao.insertRole(attackRole)
            dao.insertRole(defenseRole)

            // We need the role IDs generated by DB. Since we inserted them sequentially,
            // and it's a fresh DB, we can assume ID 1 and 2, but let's be safe.
            // Actually, insert returns Long (rowId), but Role has @PrimaryKey(autoGenerate = true).
            // Let's re-fetch them or use insert returning ID.
            // PlayerDao.insertRole returns Unit in the interface? No, suspend fun insertRole(role: Role)
            // It's defined as suspend fun insertRole(role: Role) in PlayerDao.kt, so it returns Unit.
            // I'll fetch them back.
            val roles = dao.getAllRoles().first()
            attackRole = roles.find { it.category == "ATTACCO" }!!
            defenseRole = roles.find { it.category == "DIFESA" }!!
        }

    @After
    fun closeDb() {
        db.close()
    }

    @Test
    fun testTopScorerFilteringIssue() =
        runBlocking {
            // Insert 10 Attackers with 20 goals each
            for (i in 1..10) {
                val player = Player(playerName = "Attacker $i", goals = 20, appearances = 10)
                val playerId = dao.insert(player).toInt()
                dao.insertPlayerRoles(listOf(PlayerRoleCrossRef(playerId, attackRole.roleId)))
            }

            // Insert 1 Defender with 10 goals
            val defender = Player(playerName = "Defender 1", goals = 10, appearances = 10)
            val defenderId = dao.insert(defender).toInt()
            dao.insertPlayerRoles(listOf(PlayerRoleCrossRef(defenderId, defenseRole.roleId)))

            // Get Top 10 Scorers (Current behavior)
            // This should return the 10 attackers because they have more goals.
            val topScorers = dao.getTopScorers(10).first()

            assertEquals("Should return 10 players", 10, topScorers.size)
            assertTrue("All top scorers should be attackers", topScorers.all { it.roles.any { r -> r.category == "ATTACCO" } })

            // Now, simulate the ViewModel logic: Filter this list for DEFENSE
            val defenseScorers = topScorers.filter { it.roles.any { r -> r.category == "DIFESA" } }

            // Assert that we found NO defenders, even though "Defender 1" has 10 goals and exists in DB.
            // This confirms the issue: valid top scorers for a specific category are lost if not in global top N.
            assertTrue("Should not find any defenders in the top 10 overall list", defenseScorers.isEmpty())

            // Verify the defender actually exists in DB
            val allPlayers = dao.getAllPlayers().first()
            val foundDefender = allPlayers.find { it.player.playerName == "Defender 1" }
            assertTrue("Defender should exist in DB", foundDefender != null)

            // NOW: Test the FIX
            // Use the new DAO method
            val correctDefenseScorers = dao.getTopScorersByRoleCategories(10, listOf("DIFESA")).first()

            assertEquals("Should find 1 defender", 1, correctDefenseScorers.size)
            assertEquals("Should be Defender 1", "Defender 1", correctDefenseScorers[0].player.playerName)
        }
}
