name: Android CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: 1. Check out repository
      uses: actions/checkout@v4

    - name: 2. Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: 3. Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: 4. Run tests for all modules
      run: ./gradlew test

    - name: 5. Build debug APKs for all modules
      run: ./gradlew assembleDebug

    - name: 6. Upload Mobile App APK
      uses: actions/upload-artifact@v4
      with:
        name: mobile-app-debug.apk
        path: mobile/build/outputs/apk/debug/mobile-debug.apk

    - name: 7. Upload Wear OS App APK
      uses: actions/upload-artifact@v4
      with:
        name: wear-app-debug.apk
        path: wear/build/outputs/apk/debug/wear-debug.apk
